### ISSUE TITLE
WHAT!???? WHY ONLY 2 GENDER???????

### ISSUE THREAD

**Issue by faketogosamogo** [svetlimladenov/SimpleSocial#20]
namespace SimpleSocial.Data.Models
{
    public enum Gender
    {
        Male = 1,
        Famale = 2
    }
}

**Comment by svetlimladenov** [comment]
Good one 😄 IMO all these enums should be added as Nomenclatures in the DB (even in a separate Database ("Bounded Context"🚀))

**Comment by faketogosamogo** [comment]
Okey 😆😆😆
